<?php
/**
 * Created by PhpStorm.
 * User: markuselser
 * Date: 30.05.18
 * Time: 10:18
 */

// Daten aus inkludierender Datei

// $xmlArr => $xmlArray
// $pdo -> Datenbankverbindung

if(empty($xmlArr) || !is_array($xmlArr)) {
    $xmlArr = [];
}
if(!isset($pso)) {
    $pdo = null;
}

echo "<pre>";
var_dump($xmlArr, true);
echo "</pre>";

/**
 * Newst Testdatensatz anlegen
 *
 */


exit("MacExit - ".__FILE__." Z: ".__LINE__);
